openapi: 3.0.1
info:
  title: Mullvad App API
  version: "1"
servers:
- url: /app
paths:
  /v1/relays:
    get:
      responses:
        "200":
          content:
            application/json:
              example:
                locations:
                  se-got:
                    city: Gothenburg
                    country: Sweden
                    latitude: 57.70887
                    longitude: 11.97456
                  se-sto:
                    city: Stockholm
                    country: Sweden
                    latitude: 57.70887
                    longitude: 11.97456
                openvpn:
                  ports:
                  - port: 1300
                    protocol: udp
                  - port: 443
                    protocol: tcp
                  relays:
                  - hostname: se-got-001
                    active: true
                    owned: true
                    location: se-got
                    provider: "31173"
                    ipv4_addr_in: 185.213.154.66
                    weight: 100
                    include_in_country: true
                wireguard:
                  port_ranges:
                  - - 53
                    - 53
                  - - 123
                    - 123
                  - - 443
                    - 443
                  - - 4000
                    - 33433
                  - - 33565
                    - 51820
                  - - 52001
                    - 60000
                  ipv4_gateway: 10.64.0.1
                  ipv6_gateway: fc00:bbbb:bbbb:bb01::1
                  relays:
                  - hostname: se3-wireguard
                    active: true
                    owned: true
                    location: se-got
                    provider: "31173"
                    ipv4_addr_in: 185.213.154.66
                    ipv6_addr_in: 2a03:1b20:5:f011:31::a03f
                    weight: 100
                    include_in_country: true
                    public_key: 5JMPeO7gXIbR5CnUa/NPNK4L5GqUnreF0/Bozai4pl4=
                bridge:
                  shadowsocks:
                  - protocol: tcp
                    port: 443
                    cipher: chacha20
                    password: password
                  relays:
                  - hostname: se-sto-br-001
                    active: true
                    owned: true
                    location: se-sto
                    provider: "31173"
                    ipv4_addr_in: 185.213.154.66
                    weight: 100
                    include_in_country: true
              schema:
                $ref: '#/components/schemas/_v1_relays_get_200_response'
          description: Relay list
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      summary: Relay list
  /v1/api-addrs:
    get:
      responses:
        "200":
          content:
            application/json:
              example:
              - 45.83.222.100:443
              schema:
                items:
                  type: string
                type: array
          description: 200 response
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      summary: List IP addresses for reaching the API
  /v1/me:
    get:
      deprecated: true
      responses:
        "200":
          content:
            application/json:
              example:
                token: "1234123412341234"
                expires: 2020-02-28T12:49:20+00:00
              schema:
                $ref: '#/components/schemas/_v1_me_get_200_response'
          description: 200 response
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      security:
      - AccessToken: []
      - TokenAuth: []
      summary: Get info about account
  /v1/accounts:
    post:
      deprecated: true
      responses:
        "201":
          content:
            application/json:
              example:
                token: "1234123412341234"
                expires: 2020-02-28T12:49:20+00:00
              schema:
                $ref: '#/components/schemas/_v1_me_get_200_response'
          description: 201 response
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      summary: Create account
  /v1/submit-voucher:
    post:
      requestBody:
        content:
          application/json:
            example:
              voucher_code: ABCD-EFGH-1234-5678
            schema:
              $ref: '#/components/schemas/_v1_submit_voucher_post_request'
      responses:
        "200":
          content:
            application/json:
              example:
                time_added: 2592000
                new_expiry: 2020-02-28T12:49:20+00:00
              schema:
                $ref: '#/components/schemas/_v1_submit_voucher_post_200_response'
          description: 200 response
        "400":
          content:
            application/json:
              examples:
                MISSING_ARGUMENT:
                  value:
                    code: MISSING_ARGUMENT
                    error: One of the required arguments is missing from the request
                      body
                INVALID_VOUCHER:
                  value:
                    code: INVALID_VOUCHER
                    error: This voucher code is invalid
                VOUCHER_USED:
                  value:
                    code: VOUCHER_USED
                    error: This voucher code has already been used
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Error when submitting voucher
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      security:
      - TokenAuth: []
      summary: Submit a voucher
  /v1/problem-report:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_problem_report_post_request'
      responses:
        "204":
          description: 204 response
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      summary: Submit a problem report
  /v1/www-auth-token:
    post:
      responses:
        "200":
          content:
            application/json:
              example:
                auth_token: 767b3b8d63944e5ab8751c382ad3b30f
              schema:
                $ref: '#/components/schemas/_v1_www_auth_token_post_200_response'
          description: 200 response
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      security:
      - TokenAuth: []
      summary: Request a website auth token (valid for 1 hour)
  /v1/releases/{platform}/{version}:
    get:
      parameters:
      - explode: false
        in: path
        name: platform
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                supported: true
                latest: "2020.3"
                latest_stable: "2020.3"
                latest_beta: 2020.4-beta1
              schema:
                $ref: '#/components/schemas/_v1_releases__platform___version__get_200_response'
          description: 200 response
        "404":
          content:
            application/json:
              example:
                code: RELEASE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Release not found
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      summary: Information about app release
  /v1/wireguard-keys:
    post:
      deprecated: true
      requestBody:
        content:
          application/json:
            example:
              pubkey: abdXKwUtjpSJTAA5lLphhUqfmDP8G/SK78uH9NG0rC0=
            schema:
              $ref: '#/components/schemas/_v1_wireguard_keys_post_request'
      responses:
        "201":
          content:
            application/json:
              example:
                id: abdXKwUtjpSJTAA5lLphhUqfmDP8G%2FSK78uH9NG0rC0%3D
                pubkey: abdXKwUtjpSJTAA5lLphhUqfmDP8G/SK78uH9NG0rC0=
                ipv4_address: 10.99.0.1/32
                ipv6_address: fc00:bbbb:bbbb:bb01::1/128
              schema:
                $ref: '#/components/schemas/WireGuardPubkey'
          description: 201 response
        "400":
          content:
            application/json:
              examples:
                MISSING_ARGUMENT:
                  value:
                    code: MISSING_ARGUMENT
                    error: One of the required arguments is missing from the request
                      body
                INVALID_PUBKEY:
                  value:
                    code: INVALID_PUBKEY
                    error: '"pubkey" is not a valid WireGuard public key'
                KEY_LIMIT_REACHED:
                  value:
                    code: KEY_LIMIT_REACHED
                    error: Account already has the maximum number of devices
                PUBKEY_IN_USE:
                  value:
                    code: PUBKEY_IN_USE
                    error: WireGuard public key in use by other account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Error when adding a WireGuard key
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      security:
      - TokenAuth: []
      summary: Add WireGuard public key
  /v1/wireguard-keys/{pubkey}:
    delete:
      deprecated: true
      parameters:
      - description: "The WireGuard public key, urlencoded."
        explode: false
        in: path
        name: pubkey
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: 204 response
        "404":
          content:
            application/json:
              examples:
                PUBKEY_NOT_FOUND:
                  value:
                    code: PUBKEY_NOT_FOUND
                    error: The requested pubkey does not exist
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: WireGuard key error
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      security:
      - TokenAuth: []
      summary: Delete WireGuard public key
    get:
      deprecated: true
      parameters:
      - description: "The WireGuard public key, urlencoded."
        explode: false
        in: path
        name: pubkey
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                ipv4_address: 10.99.0.1/32
                ipv6_address: fc00:bbbb:bbbb:bb01::1/128
                id: abdXKwUtjpSJTAA5lLphhUqfmDP8G%2FSK78uH9NG0rC0%3D
                pubkey: abdXKwUtjpSJTAA5lLphhUqfmDP8G/SK78uH9NG0rC0=
              schema:
                $ref: '#/components/schemas/WireGuardPubkey'
          description: 200 response
        "404":
          content:
            application/json:
              examples:
                PUBKEY_NOT_FOUND:
                  value:
                    code: PUBKEY_NOT_FOUND
                    error: The requested pubkey does not exist
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: WireGuard key error
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      security:
      - TokenAuth: []
      summary: Get WireGuard public key
  /v1/replace-wireguard-key:
    post:
      deprecated: true
      requestBody:
        content:
          application/json:
            example:
              old: abdXKwUtjpSJTAA5lLphhUqfmDP8G/SK78uH9NG0rC0=
              new: veGD6/aEY6sMfN3Ls7YWPmNgu3AheO7nQqsFT47YSws=
            schema:
              $ref: '#/components/schemas/_v1_replace_wireguard_key_post_request'
      responses:
        "200":
          content:
            application/json:
              example:
                id: abdXKwUtjpSJTAA5lLphhUqfmDP8G%2FSK78uH9NG0rC0%3D
                pubkey: abdXKwUtjpSJTAA5lLphhUqfmDP8G/SK78uH9NG0rC0=
                ipv4_address: 10.99.0.1/32
                ipv6_address: fc00:bbbb:bbbb:bb01::1/128
              schema:
                $ref: '#/components/schemas/WireGuardPubkey'
          description: The new key already exists on the account
        "201":
          content:
            application/json:
              example:
                id: abdXKwUtjpSJTAA5lLphhUqfmDP8G%2FSK78uH9NG0rC0%3D
                pubkey: abdXKwUtjpSJTAA5lLphhUqfmDP8G/SK78uH9NG0rC0=
                ipv4_address: 10.99.0.1/32
                ipv6_address: fc00:bbbb:bbbb:bb01::1/128
              schema:
                $ref: '#/components/schemas/WireGuardPubkey'
          description: The old key was removed and the new key was added
        "400":
          content:
            application/json:
              examples:
                MISSING_ARGUMENT:
                  value:
                    code: MISSING_ARGUMENT
                    error: One of the required arguments is missing from the request
                      body
                INVALID_PUBKEY:
                  value:
                    code: INVALID_PUBKEY
                    error: '"new" is not a valid WireGuard public key'
                PUBKEY_IN_USE:
                  value:
                    code: PUBKEY_IN_USE
                    error: WireGuard public key in use by other account
                RELAY_PUBKEY:
                  value:
                    code: RELAY_PUBKEY
                    error: WireGuard public key in use by a relay
                KEY_LIMIT_REACHED:
                  value:
                    code: KEY_LIMIT_REACHED
                    error: Account already has the maximum number of devices
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Error when replacing a WireGuard key
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              example:
                code: INTERNAL_ERROR
                error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal server error
      security:
      - TokenAuth: []
      summary: Replace a WireGuard pubkey
  /v1/create-apple-payment:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_create_apple_payment_post_request'
      responses:
        "200":
          content:
            application/json:
              example:
                time_added: 0
                new_expiry: 2020-02-28T12:49:20+00:00
              schema:
                $ref: '#/components/schemas/_v1_submit_voucher_post_200_response'
          description: All transactions in the receipt already exists and no time
            was added
        "201":
          content:
            application/json:
              example:
                time_added: 2592000
                new_expiry: 2020-02-28T12:49:20+00:00
              schema:
                $ref: '#/components/schemas/_v1_submit_voucher_post_200_response'
          description: New transaction(s) have been added and account expiry updated
        "400":
          content:
            application/json:
              examples:
                MISSING_ARGUMENT:
                  value:
                    code: MISSING_ARGUMENT
                    error: One of the required arguments is missing from the request
                      body
                APPLE_PRODUCT_DOES_NOT_EXIST:
                  value:
                    code: APPLE_PRODUCT_DOES_NOT_EXIST
                    error: A selected product does not exist
                APPLE_RECEIPT_ERROR:
                  value:
                    code: APPLE_RECEIPT_ERROR
                    error: The Apple receipt is not valid
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Error when making an Apple In-App payment
        "401":
          content:
            application/json:
              example:
                code: INVALID_AUTH
                error: Invalid auth header
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Access token is missing or invalid.
        "403":
          content:
            application/json:
              example:
                code: INVALID_ACCOUNT
                error: Invalid Mullvad account
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Permission denied
        "500":
          content:
            application/json:
              examples:
                APPLE_SERVER_CONNECTION_ERROR:
                  value:
                    code: APPLE_SERVER_CONNECTION_ERROR
                    error: A problem occurred when connecting to the Apple server
                INTERNAL_ERROR:
                  value:
                    code: INTERNAL_ERROR
                    error: Internal server error
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Internal error when making an Apple In-App payment
      security:
      - TokenAuth: []
      summary: Create an Apple In-App payment
components:
  parameters:
    WireGuardPubKey:
      description: "The WireGuard public key, urlencoded."
      explode: false
      in: path
      name: pubkey
      required: true
      schema:
        type: string
      style: simple
  responses:
    InvalidAuthError:
      content:
        application/json:
          example:
            code: INVALID_AUTH
            error: Invalid auth header
          schema:
            $ref: '#/components/schemas/ErrorSchema'
      description: Access token is missing or invalid.
    PermissionDeniedError:
      content:
        application/json:
          example:
            code: INVALID_ACCOUNT
            error: Invalid Mullvad account
          schema:
            $ref: '#/components/schemas/ErrorSchema'
      description: Permission denied
    InternalServerError:
      content:
        application/json:
          example:
            code: INTERNAL_ERROR
            error: Internal server error
          schema:
            $ref: '#/components/schemas/ErrorSchema'
      description: Internal server error
  schemas:
    ErrorSchema:
      example:
        code: code
        error: error
      properties:
        code:
          description: The error code.
          type: string
        error:
          description: The error message.
          type: string
      type: object
    Location:
      example:
        country: country
        city: city
        latitude: 0.8008281904610115
        longitude: 6.027456183070403
      properties:
        city:
          type: string
        country:
          type: string
        latitude:
          type: number
        longitude:
          type: number
      type: object
    WireGuardPubkey:
      example:
        ipv6_address: ipv6_address
        ipv4_address: ipv4_address
        id: id
        pubkey: pubkey
      properties:
        id:
          description: "Convenience field with the public key encoded to use with\
            \ the API (eg when deleting it), same as the pubkey field but urlencoded."
          type: string
        pubkey:
          description: The WireGuard public key.
          type: string
        ipv4_address:
          description: The ipv4 peer adress for WireGuard. Note that the mask may
            be bigger then a single IP.
          type: string
        ipv6_address:
          description: The ipv6 peer address for WireGuard. Note that the mask may
            be bigger then a single IP.
          type: string
      type: object
    Relay:
      properties:
        hostname:
          type: string
        location:
          type: string
        active:
          type: boolean
        owned:
          type: boolean
        provider:
          type: string
        ipv4_addr_in:
          type: string
        include_in_country:
          type: boolean
        weight:
          type: integer
      type: object
    OpenVpnRelay:
      allOf:
      - $ref: '#/components/schemas/Relay'
      example:
        hostname: hostname
        provider: provider
        owned: true
        include_in_country: true
        active: true
        weight: 5
        location: location
        ipv4_addr_in: ipv4_addr_in
    WireGuardRelay:
      allOf:
      - $ref: '#/components/schemas/Relay'
      - properties:
          public_key:
            type: string
          ipv6_addr_in:
            type: string
          same_ip:
            default: true
            description: |
              Whether the server supports clients using the same IP address. This flag will be removed once all servers support the feature, so clients should default to True if it's missing.
            type: boolean
          daita:
            default: false
            description: |
              If true, clients can expect DAITA to be available on this relay. Note that this field is not guaranteed to be present. A missing `daita` property is semantically equivalent to `"daita": false`.
            type: boolean
      example:
        public_key: public_key
        ipv6_addr_in: ipv6_addr_in
        hostname: hostname
        same_ip: true
        provider: provider
        owned: true
        daita: false
        include_in_country: true
        active: true
        weight: 2
        location: location
        ipv4_addr_in: ipv4_addr_in
    BridgeRelay:
      allOf:
      - $ref: '#/components/schemas/Relay'
      example:
        hostname: hostname
        provider: provider
        owned: true
        include_in_country: true
        active: true
        weight: 9
        location: location
        ipv4_addr_in: ipv4_addr_in
    _v1_relays_get_200_response_openvpn_ports_inner:
      example:
        protocol: protocol
        port: 1.4658129805029452
      properties:
        port:
          type: number
        protocol:
          type: string
      type: object
    _v1_relays_get_200_response_openvpn:
      example:
        relays:
        - hostname: hostname
          provider: provider
          owned: true
          include_in_country: true
          active: true
          weight: 5
          location: location
          ipv4_addr_in: ipv4_addr_in
        - hostname: hostname
          provider: provider
          owned: true
          include_in_country: true
          active: true
          weight: 5
          location: location
          ipv4_addr_in: ipv4_addr_in
        ports:
        - protocol: protocol
          port: 1.4658129805029452
        - protocol: protocol
          port: 1.4658129805029452
      properties:
        ports:
          description: Pairs of port/protocol that will accept connections
          items:
            $ref: '#/components/schemas/_v1_relays_get_200_response_openvpn_ports_inner'
          type: array
        relays:
          items:
            $ref: '#/components/schemas/OpenVpnRelay'
          type: array
      type: object
    _v1_relays_get_200_response_wireguard:
      example:
        ipv6_gateway: ipv6_gateway
        relays:
        - public_key: public_key
          ipv6_addr_in: ipv6_addr_in
          hostname: hostname
          same_ip: true
          provider: provider
          owned: true
          daita: false
          include_in_country: true
          active: true
          weight: 2
          location: location
          ipv4_addr_in: ipv4_addr_in
        - public_key: public_key
          ipv6_addr_in: ipv6_addr_in
          hostname: hostname
          same_ip: true
          provider: provider
          owned: true
          daita: false
          include_in_country: true
          active: true
          weight: 2
          location: location
          ipv4_addr_in: ipv4_addr_in
        port_ranges:
        - - 5
          - 5
        - - 5
          - 5
        ipv4_gateway: ipv4_gateway
      properties:
        port_ranges:
          description: List of port ranges that will accept connections
          items:
            items:
              type: integer
            type: array
          type: array
        ipv4_gateway:
          description: "The ipv4 gateway of the server, you can ping it to check whether\
            \ a tunnel is connected or not."
          type: string
        ipv6_gateway:
          description: "The ipv6 gateway of the server, you can ping it to check whether\
            \ a tunnel is connected or not."
          type: string
        relays:
          items:
            $ref: '#/components/schemas/WireGuardRelay'
          type: array
      type: object
    _v1_relays_get_200_response_bridge_shadowsocks_inner:
      example:
        cipher: cipher
        protocol: protocol
        password: password
        port: 7
      properties:
        protocol:
          type: string
        port:
          type: integer
        cipher:
          type: string
        password:
          type: string
      type: object
    _v1_relays_get_200_response_bridge:
      example:
        relays:
        - hostname: hostname
          provider: provider
          owned: true
          include_in_country: true
          active: true
          weight: 9
          location: location
          ipv4_addr_in: ipv4_addr_in
        - hostname: hostname
          provider: provider
          owned: true
          include_in_country: true
          active: true
          weight: 9
          location: location
          ipv4_addr_in: ipv4_addr_in
        shadowsocks:
        - cipher: cipher
          protocol: protocol
          password: password
          port: 7
        - cipher: cipher
          protocol: protocol
          password: password
          port: 7
      properties:
        shadowsocks:
          description: List of connection specs for Shadowsocks ports
          items:
            $ref: '#/components/schemas/_v1_relays_get_200_response_bridge_shadowsocks_inner'
          type: array
        relays:
          items:
            $ref: '#/components/schemas/BridgeRelay'
          type: array
      type: object
    _v1_relays_get_200_response:
      example:
        locations:
          key:
            country: country
            city: city
            latitude: 0.8008281904610115
            longitude: 6.027456183070403
        bridge:
          relays:
          - hostname: hostname
            provider: provider
            owned: true
            include_in_country: true
            active: true
            weight: 9
            location: location
            ipv4_addr_in: ipv4_addr_in
          - hostname: hostname
            provider: provider
            owned: true
            include_in_country: true
            active: true
            weight: 9
            location: location
            ipv4_addr_in: ipv4_addr_in
          shadowsocks:
          - cipher: cipher
            protocol: protocol
            password: password
            port: 7
          - cipher: cipher
            protocol: protocol
            password: password
            port: 7
        wireguard:
          ipv6_gateway: ipv6_gateway
          relays:
          - public_key: public_key
            ipv6_addr_in: ipv6_addr_in
            hostname: hostname
            same_ip: true
            provider: provider
            owned: true
            daita: false
            include_in_country: true
            active: true
            weight: 2
            location: location
            ipv4_addr_in: ipv4_addr_in
          - public_key: public_key
            ipv6_addr_in: ipv6_addr_in
            hostname: hostname
            same_ip: true
            provider: provider
            owned: true
            daita: false
            include_in_country: true
            active: true
            weight: 2
            location: location
            ipv4_addr_in: ipv4_addr_in
          port_ranges:
          - - 5
            - 5
          - - 5
            - 5
          ipv4_gateway: ipv4_gateway
        openvpn:
          relays:
          - hostname: hostname
            provider: provider
            owned: true
            include_in_country: true
            active: true
            weight: 5
            location: location
            ipv4_addr_in: ipv4_addr_in
          - hostname: hostname
            provider: provider
            owned: true
            include_in_country: true
            active: true
            weight: 5
            location: location
            ipv4_addr_in: ipv4_addr_in
          ports:
          - protocol: protocol
            port: 1.4658129805029452
          - protocol: protocol
            port: 1.4658129805029452
      properties:
        locations:
          additionalProperties:
            $ref: '#/components/schemas/Location'
          type: object
        openvpn:
          $ref: '#/components/schemas/_v1_relays_get_200_response_openvpn'
        wireguard:
          $ref: '#/components/schemas/_v1_relays_get_200_response_wireguard'
        bridge:
          $ref: '#/components/schemas/_v1_relays_get_200_response_bridge'
      type: object
    _v1_me_get_200_response:
      example:
        expires: expires
        token: token
      properties:
        token:
          type: string
        expires:
          type: string
      type: object
    _v1_submit_voucher_post_request:
      properties:
        voucher_code:
          type: string
      required:
      - voucher_code
      type: object
    _v1_submit_voucher_post_200_response:
      example:
        new_expiry: new_expiry
        time_added: 0.8008281904610115
      properties:
        time_added:
          type: number
        new_expiry:
          type: string
      type: object
    _v1_problem_report_post_request:
      properties:
        address:
          type: string
        message:
          type: string
        log:
          type: string
        metadata:
          type: object
      required:
      - log
      - metadata
      type: object
    _v1_www_auth_token_post_200_response:
      example:
        auth_token: auth_token
      properties:
        auth_token:
          type: string
      type: object
    _v1_releases__platform___version__get_200_response:
      example:
        latest_stable: latest_stable
        latest_beta: latest_beta
        supported: true
        latest: latest
      properties:
        supported:
          type: boolean
        latest:
          nullable: true
          type: string
        latest_stable:
          nullable: true
          type: string
        latest_beta:
          nullable: true
          type: string
      type: object
    _v1_wireguard_keys_post_request:
      properties:
        pubkey:
          description: The WireGuard public key to add
          type: string
      required:
      - pubkey
      type: object
    _v1_replace_wireguard_key_post_request:
      properties:
        old:
          description: The WireGuard public key to remove
          type: string
        new:
          description: The WireGuard public key to add
          type: string
      required:
      - new
      - old
      type: object
    _v1_create_apple_payment_post_request:
      properties:
        receipt_string:
          description: An encrypted Base64-encoded App Store receipt
          type: string
      required:
      - receipt_string
      type: object
  securitySchemes:
    AccessToken:
      scheme: Bearer
      type: http
    TokenAuth:
      description: "**DEPRECATED** The client must send \"Token {account_token}\"\
        \ in the Authorization header."
      in: header
      name: Authorization
      type: apiKey
